export const PermissionKeys = {
    roleCreate : "roleCreate",
roleGetList : "roleGetList",
roleUpdate : "roleUpdate",
roleDelete : "roleDelete",
departmentCreate : "departmentCreate",
departmentGetList : "departmentGetList",
departmentUpdate : "departmentUpdate",
departmentDelete : "departmentDelete",
accountCreate : "accountCreate",
accountGetList : "accountGetList",
accountUpdate : "accountUpdate",
accountDelete : "accountDelete",
employeeCreate : "employeeCreate",
employeeGetList : "employeeGetList",
employeeUpdate : "employeeUpdate",
employeeDelete : "employeeDelete",
}